#include <QCoreApplication>

#include <QDebug>
#include <QSettings>
#include <QRegularExpression>
#include <QRegularExpressionMatch>

#include <iostream>
#include <cctype>
#include <limits>

#include "Network/NetworkResource.h"
#include "Console/KeyboardScanner.h"

#include "Globals.h"
#include "Modbus/DataUnits.h"
#include "Modbus/ModbusSerialMaster.h"
#include "Processing/ProcessingManager.h"
#include "Processing/RequestManager.h"

#define extern
QSharedPointer<ModbusSerialMaster> serialMaster(new ModbusSerialMaster("/dev/ttyRPC0"));
#undef extern

int main(int argc, char *argv[])
{
//	ProtocolDataUnit u({1,2,3});

	QCoreApplication a(argc, argv);
	QCoreApplication::setOrganizationName("PMCS");
	QCoreApplication::setOrganizationDomain("mendl.info");
	QCoreApplication::setApplicationName("LovatoModbus");

	KeyboardScanner ks;
	QObject::connect(&ks, &KeyboardScanner::KeyPressed, &a, [&](char c){
		qDebug() << c;
		switch (toupper(c)) {
		case 'Q':
			std::cout << "Quitting...\n";
			ks.finish();
			break;

		case 'M':	// Modbus
		{
			PDUSharedPtr_t pdu(new ProtocolDataUnit({0x03, 0x00, 0x01, 0x00, 0x2A, 0x95, 0xE6}));
			ADUSharedPtr_t request(new ApplicationDataUnitSerial(static_cast<quint8>(2), pdu));

//			qDebug() << request;
			serialMaster->process(request);
		}
			break;

		/* IMPORTANT !!!
		 *
		 * As following command empirically confirmed, root of system settings of Qt
		 * on Raspberry Pi lies NOT on / but rather on /usr/local/Qt-5.5.1-raspberry
		 * i.e. master Modbus cfg file is the
		 * /usr/local/Qt-5.5.1-raspberry/etc/xdg/PMCS/LovatoModbus.conf
		 */

		case 'W': // Write INI
		{
			QSettings settings(QSettings::SystemScope,"PMCS", "LovatoModbus");
			QTextStream in(stdin);
			QString str, value;

			ks.setDetection(false);
			const QRegularExpression pattern("(.*)=(.*)");
			QRegularExpressionMatch match;
			forever {
				qDebug() << "Enter KEY=VALUE:";
				str=in.readLine();
				if(str.isEmpty())
				break;

				if((match=pattern.match(str)).hasMatch()) {

					settings.setValue(match.captured(1), match.captured(2));
					qDebug().noquote() << "\twritten: " << match.captured(1) << "=" << settings.value(match.captured(1));
				}
			}
			ks.setDetection(true);
			break;
		}

		case 'R': // Read INI
		{
			QSettings settings;
			QTextStream in(stdin);
			QString str;

			ks.setDetection(false);
				qDebug() << "Enter KEY:";
				str=in.readLine();
				qDebug().noquote() << "\tread: " << str << "=" << settings.value(str);
			ks.setDetection(true);
			break;
		}

		// Check the ~/.config/PMCS/LovatoModbus.conf generated by this command
		case 'S': // Settings
		{
			QSettings settings;
			settings.beginGroup("Test");
			settings.setValue("true",true);
			settings.setValue("false",false);
			settings.endGroup();
		}
			break;

		case 'G': // Groups
		{
			QSettings active, group;
			active.beginGroup("Active");
			for(QString s : active.childKeys()) {
				qDebug() << "Group:" << s;
				group.beginGroup(s);
				qDebug() <<  group.childKeys();
				qDebug() <<  group.childGroups();
				group.endGroup();
			}
			active.endGroup();

		}
			break;

		case 'P': // Processing
		{
			QSettings settings;
			QList<QSharedPointer<RequestManager>> requestManagers;
			settings.beginGroup(REQUEST_GROUPS_KEY);
			foreach(QString group, settings.childGroups()) {
				qDebug() << "Processing group" << group;
				settings.beginGroup(group);
				requestManagers.append(QSharedPointer<RequestManager>(new RequestManager(settings)));
				settings.endGroup();
			}
			settings.endGroup();
		}

			break;

//----------------------------------

		qDebug() << "\nCOMMAND:";
		}

	}, Qt::QueuedConnection);
	QObject::connect(&ks, &KeyboardScanner::finished, &a, &QCoreApplication::quit);

	ks.start();
	if(Q_BYTE_ORDER == Q_BIG_ENDIAN)
		qDebug() << "Host uses big endianness.";
	else
		qDebug() << "Host uses little endianness.";

	if(std::numeric_limits<float>::is_iec559)
		qDebug() << "Host complies to IEEE 754.";
	else
		qDebug() << "Host does not comply to IEEE 754.";

	std::cout << "Constructing ProcessingManager object...\n\n";
	ProcessingManager p;
	std::cout << "Modbus application started...\n\n";
	int result = a.exec();
	std::cout << "Modbus application quited...\n";
	return result;
}
